spring:
  application:
    name: service
# disable cache for Spring Cloud Loadbalancer
  cache:
    type: none

  cloud:
    loadbalancer:
      ribbon:
        enabled: false # enables Spring Cloud Loadbalancer

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: uaa
            client-id: gateway
            client-secret: gatewaysecret
            authorization-grant-type: authorization_code
            scope: openid,profile,email,resource.read,resource.write
        provider:
          uaa:
            issuer-uri: http://localhost:8080/oauth/token
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/oauth/token
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true

