spring:
  application:
    name: service

  cloud:
    loadbalancer:
      ribbon:
        enabled: false # enables Spring Cloud Loadbalancer

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/oauth/token
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    registry-fetch-interval-seconds: 5
  instance:
    preferIpAddress: true
